/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_jclab_netty_channel_iocp_Native */

#ifndef _Included_kr_jclab_netty_channel_iocp_Native
#define _Included_kr_jclab_netty_channel_iocp_Native
#ifdef __cplusplus
extern "C" {
#endif
#undef kr_jclab_netty_channel_iocp_Native_INVALID_HANDLE_VALUE
#define kr_jclab_netty_channel_iocp_Native_INVALID_HANDLE_VALUE -1L
/*
 * Class:     kr_jclab_netty_channel_iocp_Native
 * Method:    createIoCompletionPort
 * Signature: (IILkr/jclab/netty/channel/iocp/IocpCompletionContext;I)I
 */
JNIEXPORT jint JNICALL Java_kr_jclab_netty_channel_iocp_Native_createIoCompletionPort
  (JNIEnv *, jclass, jint, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
