name: Test
on:
  push: {}
jobs:
  java-build:
    runs-on: windows-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "runner_arch=$(uname -m)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'
      - name: Set up Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Build native library x86_64
        run: |
          cd netty-transport-native-iocp
          .\build-native.bat x86_64
      - name: Build native library x86_32
        run: |
          cd netty-transport-native-iocp
          .\build-native.bat x86_32
      - name: Build
        run: |
          .\gradlew.bat build test